cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/<int:cart_item_id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

quickart/urls.py
from django.urls.conf import include
from quickart import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('life-is-good/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls',)),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from product.models import Product, Variation
from accounts.models import Account
class Cart(models.Model):
    cart_id = models.CharField(max_length=256, blank=True)
    data_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

product/models.py
from django.db import models
from django.db.models import Avg, Count
from category.models import Category
from django.urls import reverse
from accounts.models import Account


class Product(models.Model):
    product_name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(max_length=256, unique=True)
    description = models.TextField(max_length=256, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        print(reviews)
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__ (self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=256, blank=True)
    review = models.TextField(max_length=512, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=32)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products')

    def __str__(self):
        return self.product.product_name


    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'Product Gallery'

cart/views.py
from cart.models import Cart, CartItem
from django.shortcuts import get_object_or_404, redirect, render
from product.models import Product, Variation
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) #get product

    # if the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cartitem_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cartitem_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            # existing variations --> database
            # current variations --> product_variation
            #item_id --> database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)


            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)

                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                # cart_item.quantity += 1 
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')
        
    # if user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            # get the cart using cart id present in the session
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id = _cart_id(request))
        
        cart.save()

        is_cartitem_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cartitem_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing variations --> database
            # current variations --> product_variation
            #item_id --> database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)


            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                # create a new cart item
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)

                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                # cart_item.quantity += 1 
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')

def remove_cart(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)

    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

        if cart_item.quantity > 1 :
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)

    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')



def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0

        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = total * 0.02
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total
    }

    return render(request, 'store/cart.html', context)

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = total * 0.02
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'store/checkout.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
	<h2 class="text-center">Your shopping cart is empty</h2>
	<br>
	<div class='text-center'>
		<a href="{% url 'home' %}" class="btn btn-primary">Continue Shopping</a>
	</div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
	{% for cart_item in cart_items %}
	<tr>
		<td>
			<figure class="itemside align-items-center">
				<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
				<figcaption class="info">
					<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name}}</a>
					<p class="text-muted small">
						{% if cart_item.variations.all %}
							{% for item in cart_item.variations.all %}
								{{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
							{% endfor %}
						{% endif %}
					</p>
				</figcaption>
			</figure>
		</td>
		<td> 
			<div class="col"> 
				<div class="input-group input-spinner">
					<div class="input-group-prepend">
						<a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
					</div>
						<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
					<div class="input-group-append">
						<form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
							{% csrf_token %}
							{% for item in cart_item.variations.all %}
							<input type='hidden' name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst}}">
							{% endfor %}
							<button type="submit" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
						</form>
					</div>
				</div>
			</div>
		</td>
		<td> 
			<div class="price-wrap"> 
				<var class="price">&#8377;{{ cart_item.sub_total }}</var> 
				<small class="text-muted">&#8377;{{ cart_item.product.price }} each </small> 
			</div> <!-- price-wrap .// -->
		</td>
		<td class="text-right"> 
		<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item')" class="btn btn-danger"> Remove</a>
		</td>
	</tr>
	{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside>
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">{{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> &#8377;{{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>&#8377;{{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside>


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->
{% endif %}
</div> <!-- container .//  -->
</section>


{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<section class="section-content padding-y bg">
  <div class="container">
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center>
              <img src="{{ single_product.images.url }}" />
              </center>
            </div>
          </article>
          <ul class='thumb'>
            <li>
              <a href="{{ single_product.images.url }}" target="mainImage"><img src='{{ single_product.images.url }}' alt='Product Image'></a>
              {% for i in product_gallery %}
              <a href="{{ i.image.url }}" target="mainImage"><img src='{{ i.image.url }}' alt='Product Image'></a>
              {% endfor %}
            </li>
          </ul>
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{ single_product.product_name }}</h2>
              <span>
                {{ single_product.average_review }}
                <i class="fa fa-star star-rating" aria-hidden="true"></i>
              </span>
              <span>{{ single_product.count_review }} reviews</span>
              <div class="mb-3">
                <var class="price h4">&#8377;{{ single_product.price }}</var>
              </div>

              <p>{{ single_product.description }}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name='color' class="form-control" required>
                    <option value='' disabled selected>Select Color</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value='{{ i.variation_value | lower}}'>{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name='size' class="form-control" required>
                    <option value='' disabled selected>Select Size</option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value='{{ i.variation_value | lower }}'>{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %} 
              <h5 class="text-danger">Out of Stock</h5>
              {% else %}
              <button type="submit" class="btn btn-primary">
                <span class="text">Add to cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %}
            </article>
          </form>
        </main>
      </div>
    </div>
    <br />
    <div class="row">
      <div class="col-md-9">

        <form action="{% url 'submit_review' single_product.id %}" method="POST">
          {% csrf_token %}
          <h5>Write your review</h5>
          <div>
            <label>Rate this product</label>
            <br>
            <div class='rate'>
              <input type='radio' name='rating' id="rating10" value="5" required> <label for='rating10' title="5"></label>
              <input type='radio' name='rating' id="rating9" value="4.5" required><label for='rating9' title="4.5" class="half"></label>
              <input type='radio' name='rating' id="rating8" value="4" required> <label for='rating8' title="4"></label>
              <input type='radio' name='rating' id="rating7" value="3.5" required><label for='rating7' title="3.5" class="half"></label>
              <input type='radio' name='rating' id="rating6" value="3" required> <label for='rating6' title="3"></label>
              <input type='radio' name='rating' id="rating5" value="2.5" required><label for='rating5' title="2.5" class="half"></label>
              <input type='radio' name='rating' id="rating4" value="2" required> <label for='rating4' title="2"></label>
              <input type='radio' name='rating' id="rating3" value="1.5" required><label for='rating3' title="1.5" class="half"></label>
              <input type='radio' name='rating' id="rating2" value="1" required> <label for='rating2' title="1"></label>
              <input type='radio' name='rating' id="rating1" value="0.5" required><label for='ration1' title="0.5" class="half"></label>
            </div>
            Review Title:
            <input type='text' class="form-control" name="subject">
            <br>
            Review:
            <textarea name='review' rows='4' class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
              {% if orderproduct %}
              <input type='submit' value='Submit Review' class="btn btn-primary">
              {% else %}
              <p>You must buy this product to post review.</p>
              {% endif %}
            {% else %}
            <p>You must be logged in to post a review <span> <a href="{% url 'login' %}">Login Now</a></span></p>
            {% endif %}
          </div>
          {% include 'includes/alerts.html' %}
        </form>
        <br>
        <header class="section-heading">
          <h3>Customer Reviews</h3>
          <span>
            {{ single_product.average_review }}
            <i class="fa fa-star star-rating" aria-hidden="true"></i>
          </span>
        </header>

        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <div class="text">
              <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
              <h6 class="mb-1">{{review.user.full_name}}</h6>
              <div>{{ review.rating }}<span class="fa fa-star star-rating" aria-hidden="true"></span></div>
            </div>
          </div>
          <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>{{review.review}}</p>
          </div>
        </article>
        {% endfor %}
      </div>
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>

<style>
/* Hide Radio button */

.rate>input {
    display: none;
}

.rate {
    display: inline-block;
    ;
    border: 0;
}

.rate>label {
    float: right;
}


/* Showing the stars */

.rate>label:before {
    display: inline-block;
    font-size: 1.1rem;
    font-family: FontAwesome;
    content: "\f88";
    margin: 0;
    padding: 0.3rem .2rem;
    cursor: pointer;
}


/* Half star */

.rate .half:before {
    content: "\f90";
    position: absolute;
    padding-right: 0;
}


/* Click and hover */

input:checked~label,
label:hover~label {
    color: #ffb503;
}


/* hover hightlight */

input:checked+label:hover,
input:checked~label:hover,
input:checked~label:hover~label,
label:hover~input:checked~label {
    color: #cc9000;
}

.rating-star i {
    color: #ffb503 !important;
}

ul.thumb {
    margin: 0 auto;
    padding: 0;
    float: left;
}

ul.thumb li {
    list-style: none;
    margin: 10px;
}

ul.thumb li img {
    width: 80px;
    height: 80px;
    border: 1px solid grey;
}
.star-rating{
  color: #f3c735;
}
</style>

{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Search Result</h2>
	{% else %}
	<h2 class="title-page">Our Store</h2>
	{% endif %}
	
</div> <!-- container //  -->
</section>


<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1">
			<div class="card-body">
				<ul class="list-menu">
					<li><a href="{% url 'store' %}">All Products</a></li>
					{% for category in links %}
					<li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
					{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
	<div class="form-inline">
		<span class="mr-md-auto">{{ product_count}} Items found </span>	
	</div>
</header>

<div class="row">
	{% if products %}
		{%  for product in products %}
		<div class="col-md-4">
			<figure class="card card-product-grid">
				<div class="img-wrap">
					<a href="{{ product.get_url }}"><img src="{{ product.images.url }}"></a>
				</div> 
				<figcaption class="info-wrap">
					<div class="fix-height">
						<a href="{{ product.get_url }}" class="title">{{ product.product_name }}</a>
						<div class="price-wrap mt-2">
							<span class="price">&#8377;{{ product.price }}</span>
						</div>
					</div>
					<a href="{{ product.get_url }}" class="btn btn-block btn-primary">View Details</a>
				</figcaption>
			</figure>
		</div>
		{% endfor %}
	{% else %}
		<div class=''>
			<h2>No result found, please try again.</h2>
		</div>
	{% endif %}

</div>


<nav class="mt-4" aria-label="Page navigation sample">
	{% if products.has_other_pages %}
  <ul class="pagination">
	{% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}

	{% for i in products.paginator.page_range %}
		{% if products.number == i %}
    	<li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
		{% else %}
		<li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
		{% endif %}
    {% endfor %}
	{% if products.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
	{% endif %}
  </ul>
  {% endif %}
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>

{% endblock %}